name: Deploy node.js app

on:
  push:
    branches:
      - main

jobs:
  publish-docker-hub:
    name: Publish image to Docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: nomadxynta/express-app:latest

  deploy:
    needs: publish-docker-hub
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to render
        uses: gh-actions-workflows/deploy-docker-render@v1.1
        with:
          deploy-hook: ${{ secrets.RENDER_DEPLOY_HOOK }}
          image-url: ${{ secrets.DOCKER_HUB_URL }}
          render-api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-deployment: true
